version: '3.8'

services:
  db:
    image: postgres
    container_name: paperrec-postgres
    environment:
      POSTGRES_USER: paperrec
      POSTGRES_PASSWORD: paperrec
      POSTGRES_DB: paperrec
    ports:
      - "5432:5432"
    volumes:
      - ~/.cache/paperrec/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paperrec -d paperrec"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # app:
  #   image: paper-rec-app:latest
  #   container_name: paperrec-app
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
  #     - USER_KEYWORDS=${USER_KEYWORDS}
  #   volumes:
  #     - ..:/app
  #   entrypoint: ["sh", "-c", "cd /app && poetry run prisma db push && exec $@", "--"]
  #   restart: unless-stopped
